# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy dependency definitions
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install --frozen-lockfile

# Copy the rest of the application
COPY . .

# Build the project
RUN yarn build

# Expose the default port (if the server uses one, otherwise remove or adjust accordingly)
EXPOSE 3000

# Run the MCP server
CMD [ "node", "dist/index.js" ]
